// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFGmSAZIu-IcaqWEXIKZRFOwgOtl8oerc',
    appId: '1:1038809762351:web:ff6edfb380d1b6b09e14da',
    messagingSenderId: '1038809762351',
    projectId: 'tribbe-ed2db',
    authDomain: 'tribbe-ed2db.firebaseapp.com',
    databaseURL: 'https://tribbe-ed2db-default-rtdb.firebaseio.com',
    storageBucket: 'tribbe-ed2db.firebasestorage.app',
    measurementId: 'G-B3XYPF60DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTnJa4Guc3Im6u1qcLkvdT9T5QPUuKDSw',
    appId: '1:1038809762351:android:c49c7deebe30e07b9e14da',
    messagingSenderId: '1038809762351',
    projectId: 'tribbe-ed2db',
    databaseURL: 'https://tribbe-ed2db-default-rtdb.firebaseio.com',
    storageBucket: 'tribbe-ed2db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQRXuz1N5ZknN3fx4JVDGQMUXaQuFWLCc',
    appId: '1:1038809762351:ios:d23477b7ce5793a69e14da',
    messagingSenderId: '1038809762351',
    projectId: 'tribbe-ed2db',
    databaseURL: 'https://tribbe-ed2db-default-rtdb.firebaseio.com',
    storageBucket: 'tribbe-ed2db.firebasestorage.app',
    iosBundleId: 'com.tribbe.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.tribbe',
  );
}